development:
  adapter: mysql2
  encoding: utf8
  database: avatar_book_development
  username: root
  password: 'Rootpasswordgiven@123'
  port: 3306
  host: 127.0.0.1
  
test:
  adapter: mysql2
  encoding: utf8
  database: avatar_book_test
  username: root
  password: 'Rootpasswordgiven@123'
  port: 3306
  host: 127.0.0.1
 
staging:
  adapter: mysql2
  encoding: utf8
  database: avatar_book_staging
  username: root
  password: 'Rootpasswordgiven@123'
  port: 3306
  host: 127.0.0.1
 
production:
  adapter: mysql2
  encoding: utf8
  database: avatar_book_production
  username: root
  password: 'Rootpasswordgiven@123'
  port: 3306
  host: 127.0.0.1